### Variables
@apiurl = http://localhost:3000

### GET pong
# Teste para verificar se a api está no ar
GET {{apiurl}}/ping

### POST categories
# Recebe os dados para cadastrar um produto (create-product.dto)

POST {{apiurl}}/categories
Content-Type: application/json

{
  "name": "category dois",
  "description": "um testezinho basico"
}

### GET categories
GET {{apiurl}}/categories

### GET category by id
GET {{apiurl}}/categories/0d5b72fb-1b08-4313-8b4c-dadc2be2974a

### DELETE category
DELETE {{apiurl}}/categories/8a44b338-db03-4dd7-9fe3-03cdcd69732b

### UPDATE category
# Recebe os dados para modificar um produto (update-category.dto)

PUT {{apiurl}}/categories
Content-Type: application/json

{
  "id": "7e755287-3baa-4294-9f3f-52b270af9051",
  "name": "Teste Um Update",
  "description": "Teste de update"
}