### Variables
@apiurl = http://localhost:3000

### GET pong
# Teste para verificar se a api está no ar
GET {{apiurl}}/ping

### POST product
# Recebe os dados para cadastrar um produto (create-product.dto)
# {
#   "name": "teste 2",
#   "description": "um testezinho basico",
#   "price": 89,
#   "id_category": "string"
# }
POST {{apiurl}}/products
Content-Type: application/json

{
  "name": "teste 1 image null",
  "description": "um testezinho basico",
  "price": 89,
  "id_category": "0d5b72fb-1b08-4313-8b4c-dadc2be2974a",
  "image": "imageName"
}

### GET products
GET {{apiurl}}/products

### GET product by id
GET {{apiurl}}/products/12dcdd20-21c9-4262-af38-97c34791f50b

### DELETE product
DELETE {{apiurl}}/products/3ac11ef5-e823-480f-998c-7c87cc5d0ca9

### UPDATE product
# Recebe os dados para modificar um produto (update-product.dto)

PATCH  {{apiurl}}/products
Content-Type: application/json

{
  "id": "12dcdd20-21c9-4262-af38-97c34791f50b",
  "price": 35
}

###


