### Variables
@apiurl = http://localhost:80

### GET pong
# Teste para verificar se a api está no ar
GET {{apiurl}}/ping

### POST product
# Recebe os dados para cadastrar um produto (create-product.dto)
# {
#   "name": "teste 2",
#   "description": "um testezinho basico",
#   "price": 89,
#   "id_category": "string"
# }
POST {{apiurl}}/products
Content-Type: application/json

{
  "name": "teste 2 image null",
  "description": "um testezinho basico",
  "price": 89,
  "id_category": "0d5b72fb-1b08-4313-8b4c-dadc2be2974a",
  "image": "imageName"
}

### GET products
GET {{apiurl}}/products

### GET product by id
GET {{apiurl}}/products/9cce1fce-8fa0-4f07-bd4f-35311309f8d9

### DELETE product
DELETE {{apiurl}}/products/9cce1fce-8fa0-4f07-bd4f-35311309f8d9

### UPDATE product
# Recebe os dados para modificar um produto (update-product.dto)

PATCH  {{apiurl}}/products
Content-Type: application/json

{
  "id": "9cce1fce-8fa0-4f07-bd4f-35311309f8d9",
  "price": 35
}

### UPDATE product adicionando uma imagem a um produto
PATCH {{apiurl}}/products/image
Content-Type: multipart/form-data; boundary=Splitter

--Splitter
Content-Disposition: form-data; name="id"

9cce1fce-8fa0-4f07-bd4f-35311309f8d9
--Splitter
Content-Disposition: form-data; name="image"; filename="P1.jpg" 
Content-Type: image/jpeg

< /home/gfhuff/Pictures/P1.jpg
--Splitter--



