### Variables
@apiurl = http://localhost:3000

### GET pong
# Teste para verificar se a api está no ar
GET {{apiurl}}/ping

### POST product
# Recebe os dados para cadastrar um produto (create-product.dto)
# {
#   "name": "teste 2",
#   "description": "um testezinho basico",
#   "price": 89,
#   "id_category": "string"
# }
POST {{apiurl}}/products
Content-Type: application/json

{
  "name": "teste 1",
  "description": "um testezinho basico",
  "price": 89,
  "id_category": "582fbe83-b558-4d4e-9678-0de9d09fced9",
  "image": "imageName"
}

### GET products
GET {{apiurl}}/products

### GET product by id
GET {{apiurl}}/products/3ac11ef5-e823-480f-998c-7c87cc5d0ca9

### DELETE product
DELETE {{apiurl}}/products/3ac11ef5-e823-480f-998c-7c87cc5d0ca9

### UPDATE product
# Recebe os dados para modificar um produto (update-product.dto)

PUT {{apiurl}}/products
Content-Type: application/json

{
  "id": "8948641d-7e6e-4b75-900c-1a70652e9db5",
  "price": 22.99
}